In [60]:
# Import Libaries

import requests
import json
import pandas as pd

#Create function to pull JSON data from CDC API

def CDC_Pull (ThemeId):
    url = "https://nccd.cdc.gov/DHDSPAtlas/proxy.ashx?https://proxy/api/data"
    payload = json.dumps({
      "CountyVersion": "2018",
      "GeographyType": "county",
      "ParentGeographyFilter": "",
      "ThemeClassId": 2,
      "ThemeFilterOptions": [],
      "ThemeId": ThemeId,
      "ThemeSubClassId": 13
    }, indent=4)
    headers = {
      'Content-Type': 'application/json',
      'Cookie': 'TS01ae363a=015d0abe8785e5b669589a99d047712fb1a00a60e1bccd9ee6909e7b2919ccad01d4b5ace6a65d1b843858eac8ee73347cee59aaf5'
    }
    response = requests.request("POST", url, headers=headers, data=payload)
    return response

# Request for the Percent of Black Population by County

Black_Pop_TID = 38

#Ensure correct JSON formatting

res = CDC_Pull(Black_Pop_TID).json()

# Convert RAW JSON into DataFrame

Json_DF_B = pd.json_normalize(res['Data'])

# Rename Value to Correct Column title, will change for every COl
## Display DataFrame

json_df_Black_POP = Json_DF_B.rename(columns={'Value': 'Percent of Black Population'})
json_df_Black_POP

,CensusTractName,DisplayText,Key,ParentText,ThemeRangeId,Percent of Black Population
0,None,American Samoa,60000,AS,0,-1.0
1,None,Guam,66010,GU,0,-1.0
2,None,Mariana Islands,69000,MP,0,-1.0
3,None,Saint Croix (County Equivalent),78010,VI,0,-1.0
4,None,Saint John (County Equivalent),78020,VI,0,-1.0
...,...,...,...,...,...,...
3221,None,Greene,01063,AL,5,79.5
3222,None,Macon,01087,AL,5,81.7
3223,None,Holmes,28051,MS,5,83.7
3224,None,Jefferson,28063,MS,5,85.8
3225,None,Claiborne,28021,MS,5,87.4

In [51]:
# Request for the Percent of Native American Population by County
Native_Pop_TID = 39

#Ensure correct JSON formatting

res_N = CDC_Pull(Native_Pop_TID).json()

# Convert RAW JSON into DataFrame

Json_DF_N = pd.json_normalize(res_N['Data'])
Json_DF_N

# Rename Value to Correct Column title, will change for every COl
## Display DataFrame

json_df_NATIVE_POP = Json_DF_N.rename(columns={'Value': 'Percent of Native American Population'})
json_df_NATIVE_POP

,CensusTractName,DisplayText,Key,ParentText,ThemeRangeId,Percent of Native American Population
0,None,American Samoa,60000,AS,0,-1.0
1,None,Guam,66010,GU,0,-1.0
2,None,Mariana Islands,69000,MP,0,-1.0
3,None,Saint Croix (County Equivalent),78010,VI,0,-1.0
4,None,Saint John (County Equivalent),78020,VI,0,-1.0
...,...,...,...,...,...,...
3221,None,Bethel,02050,AK,5,82.2
3222,None,Buffalo,46017,SD,5,82.3
3223,None,Northwest Arctic,02188,AK,5,82.4
3224,None,Oglala Lakota,46102,SD,5,89.5
3225,None,Kusilvak,02158,AK,5,90.9

In [52]:
# Request for the Percent of White Population by County

White_Pop_TID = 55

#Ensure correct JSON formatting

res_W = CDC_Pull(White_Pop_TID).json()

# Convert RAW JSON into DataFrame

Json_DF_W = pd.json_normalize(res_W['Data'])

# Rename Value to Correct Column title, will change for every COl
## Display DataFrame

json_df_White_POP = Json_DF_W.rename(columns={'Value': 'Percent of White Population'})
json_df_White_POP

,CensusTractName,DisplayText,Key,ParentText,ThemeRangeId,Percent of White Population
0,None,American Samoa,60000,AS,0,-1.0
1,None,Guam,66010,GU,0,-1.0
2,None,Mariana Islands,69000,MP,0,-1.0
3,None,Saint Croix (County Equivalent),78010,VI,0,-1.0
4,None,Saint John (County Equivalent),78020,VI,0,-1.0
...,...,...,...,...,...,...
3221,None,Highland,51091,VA,5,99.5
3222,None,Webster,54101,WV,5,99.6
3223,None,Hanson,46061,SD,5,99.6
3224,None,Garfield,30033,MT,5,99.8
3225,None,Blaine,31009,NE,5,100.0

In [53]:
# Request for the Percent of Hispanic/Latino Population by County

Hispanic_Pop_TID = 56

#Ensure correct JSON formatting

res_H = CDC_Pull(Hispanic_Pop_TID).json()

# Convert RAW JSON into DataFrame

Json_DF_H = pd.json_normalize(res_H['Data'])

# Rename Value to Correct Column title, will change for every COl
## Display DataFrame

json_df_Hispanic_POP = Json_DF_H.rename(columns={'Value': 'Percent of Hispanic/Latino Population'})
json_df_Hispanic_POP

,CensusTractName,DisplayText,Key,ParentText,ThemeRangeId,Percent of Hispanic/Latino Population
0,None,American Samoa,60000,AS,0,-1.0
1,None,Guam,66010,GU,0,-1.0
2,None,Mariana Islands,69000,MP,0,-1.0
3,None,Saint Croix (County Equivalent),78010,VI,0,-1.0
4,None,Saint John (County Equivalent),78020,VI,0,-1.0
...,...,...,...,...,...,...
3221,None,Juana Diaz,72075,PR,5,99.8
3222,None,Hatillo,72065,PR,5,99.8
3223,None,Hormigueros,72067,PR,5,99.8
3224,None,Yabucoa,72151,PR,5,99.9
3225,None,Barranquitas,72019,PR,5,100.0

In [56]:
# Request for the Percent of Asian Population by County
Asian_Pop_TID = 40

#Ensure correct JSON formatting

res_A = CDC_Pull(Asian_Pop_TID).json()

# Convert RAW JSON into DataFrame

Json_DF_A = pd.json_normalize(res_A['Data'])

# Rename Value to Correct Column title, will change for every COl
## Display DataFrame

json_df_Asian_POP = Json_DF_A.rename(columns={'Value': 'Percent of Asian/Pacific Islander Population'})
json_df_Asian_POP

,CensusTractName,DisplayText,Key,ParentText,ThemeRangeId,Percent of Asian/Pacific Islander Population
0,None,American Samoa,60000,AS,0,-1.0
1,None,Guam,66010,GU,0,-1.0
2,None,Mariana Islands,69000,MP,0,-1.0
3,None,Saint Croix (County Equivalent),78010,VI,0,-1.0
4,None,Saint John (County Equivalent),78020,VI,0,-1.0
...,...,...,...,...,...,...
3221,None,Maui,15009,HI,5,39.1
3222,None,Kauai,15007,HI,5,40.0
3223,None,Aleutians West,02016,AK,5,42.0
3224,None,Honolulu,15003,HI,5,50.3
3225,None,Kalawao,15005,HI,5,53.3

In [58]:
# Request for the Percent of Retirement Population by County
Retirement_Pop_TID = 34

#Ensure correct JSON formatting

res_R = CDC_Pull(Retirement_Pop_TID).json()

# Convert RAW JSON into DataFrame

Json_DF_R = pd.json_normalize(res_R['Data'])

# Rename Value to Correct Column title, will change for every COl
## Display DataFrame

json_df_Retirement_POP = Json_DF_R.rename(columns={'Value': 'Percent of Retired Population'})
json_df_Retirement_POP

,CensusTractName,DisplayText,Key,ParentText,ThemeRangeId,Percent of Retired Population
0,None,American Samoa,60000,AS,0,-1.0
1,None,Guam,66010,GU,0,-1.0
2,None,Mariana Islands,69000,MP,0,-1.0
3,None,Saint Croix (County Equivalent),78010,VI,0,-1.0
4,None,Saint John (County Equivalent),78020,VI,0,-1.0
...,...,...,...,...,...,...
3221,None,La Paz,04012,AZ,5,37.9
3222,None,Harding,35021,NM,5,38.3
3223,None,Catron,35003,NM,5,38.5
3224,None,Charlotte,12015,FL,5,39.0
3225,None,Sumter,12119,FL,5,55.6

In [65]:
#Merge Native American and Black Pop Dataframes
Merged_DF = pd.merge(json_df_Black_POP,json_df_NATIVE_POP,left_on='Key',right_on='Key')
#Drop redundent COL.
Merged_DF = Merged_DF.drop(['CensusTractName_y','DisplayText_y','ParentText_y','ThemeRangeId_y'], axis=1)
Merged_DF

,CensusTractName_x,DisplayText_x,Key,ParentText_x,ThemeRangeId_x,Percent of Black Population,Percent of Native American Population
0,None,American Samoa,60000,AS,0,-1.0,-1.0
1,None,Guam,66010,GU,0,-1.0,-1.0
2,None,Mariana Islands,69000,MP,0,-1.0,-1.0
3,None,Saint Croix (County Equivalent),78010,VI,0,-1.0,-1.0
4,None,Saint John (County Equivalent),78020,VI,0,-1.0,-1.0
...,...,...,...,...,...,...,...
3221,None,Greene,01063,AL,5,79.5,0.5
3222,None,Macon,01087,AL,5,81.7,0.2
3223,None,Holmes,28051,MS,5,83.7,0.0
3224,None,Jefferson,28063,MS,5,85.8,0.1
3225,None,Claiborne,28021,MS,5,87.4,0.1

In [68]:
#Merge White Pop into main DataFrame
Merged_DF2 = pd.merge(Merged_DF,json_df_White_POP,left_on='Key',right_on='Key')
#Drop redundent COL.
Merged_DF2 = Merged_DF2.drop(['CensusTractName','DisplayText','ParentText','ThemeRangeId'], axis=1)
Merged_DF2

,CensusTractName_x,DisplayText_x,Key,ParentText_x,ThemeRangeId_x,Percent of Black Population,Percent of Native American Population,Percent of White Population
0,None,American Samoa,60000,AS,0,-1.0,-1.0,-1.0
1,None,Guam,66010,GU,0,-1.0,-1.0,-1.0
2,None,Mariana Islands,69000,MP,0,-1.0,-1.0,-1.0
3,None,Saint Croix (County Equivalent),78010,VI,0,-1.0,-1.0,-1.0
4,None,Saint John (County Equivalent),78020,VI,0,-1.0,-1.0,-1.0
...,...,...,...,...,...,...,...,...
3221,None,Greene,01063,AL,5,79.5,0.5,17.1
3222,None,Macon,01087,AL,5,81.7,0.2,15.5
3223,None,Holmes,28051,MS,5,83.7,0.0,15.6
3224,None,Jefferson,28063,MS,5,85.8,0.1,13.0
3225,None,Claiborne,28021,MS,5,87.4,0.1,11.6

In [70]:
#Merge Hispanic/Latino Pop into Main Dataframe
Merged_DF3 = pd.merge(Merged_DF2,json_df_Hispanic_POP,left_on='Key',right_on='Key')
#Drop redundent COL.
Merged_DF3 = Merged_DF3.drop(['CensusTractName','DisplayText','ParentText','ThemeRangeId'], axis=1)
Merged_DF3

,CensusTractName_x,DisplayText_x,Key,ParentText_x,ThemeRangeId_x,Percent of Black Population,Percent of Native American Population,Percent of White Population,Percent of Hispanic/Latino Population
0,None,American Samoa,60000,AS,0,-1.0,-1.0,-1.0,-1.0
1,None,Guam,66010,GU,0,-1.0,-1.0,-1.0,-1.0
2,None,Mariana Islands,69000,MP,0,-1.0,-1.0,-1.0,-1.0
3,None,Saint Croix (County Equivalent),78010,VI,0,-1.0,-1.0,-1.0,-1.0
4,None,Saint John (County Equivalent),78020,VI,0,-1.0,-1.0,-1.0,-1.0
...,...,...,...,...,...,...,...,...,...
3221,None,Greene,01063,AL,5,79.5,0.5,17.1,1.6
3222,None,Macon,01087,AL,5,81.7,0.2,15.5,1.7
3223,None,Holmes,28051,MS,5,83.7,0.0,15.6,0.2
3224,None,Jefferson,28063,MS,5,85.8,0.1,13.0,0.3
3225,None,Claiborne,28021,MS,5,87.4,0.1,11.6,0.1

In [73]:
#Merge Asian Pop into Main Dataframe
Merged_DF4 = pd.merge(Merged_DF3,json_df_Asian_POP,left_on='Key',right_on='Key')
#Drop redundent COL.
Merged_DF4 = Merged_DF4.drop(['CensusTractName','DisplayText','ParentText','ThemeRangeId'], axis=1)
Merged_DF4

,CensusTractName_x,DisplayText_x,Key,ParentText_x,ThemeRangeId_x,Percent of Black Population,Percent of Native American Population,Percent of White Population,Percent of Hispanic/Latino Population,Percent of Asian/Pacific Islander Population
0,None,American Samoa,60000,AS,0,-1.0,-1.0,-1.0,-1.0,-1.0
1,None,Guam,66010,GU,0,-1.0,-1.0,-1.0,-1.0,-1.0
2,None,Mariana Islands,69000,MP,0,-1.0,-1.0,-1.0,-1.0,-1.0
3,None,Saint Croix (County Equivalent),78010,VI,0,-1.0,-1.0,-1.0,-1.0,-1.0
4,None,Saint John (County Equivalent),78020,VI,0,-1.0,-1.0,-1.0,-1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...
3221,None,Greene,01063,AL,5,79.5,0.5,17.1,1.6,0.0
3222,None,Macon,01087,AL,5,81.7,0.2,15.5,1.7,0.2
3223,None,Holmes,28051,MS,5,83.7,0.0,15.6,0.2,0.0
3224,None,Jefferson,28063,MS,5,85.8,0.1,13.0,0.3,0.4
3225,None,Claiborne,28021,MS,5,87.4,0.1,11.6,0.1,0.5

In [74]:
#Merge Retirement Pop into Main Dataframe
Merged_DF_Demo_Final = pd.merge(Merged_DF4,json_df_Retirement_POP,left_on='Key',right_on='Key')
#Drop redundent COL.
Merged_DF_Demo_Final = Merged_DF_Demo_Final.drop(['CensusTractName','DisplayText','ParentText','ThemeRangeId'], axis=1)
Merged_DF_Demo_Final

,CensusTractName_x,DisplayText_x,Key,ParentText_x,ThemeRangeId_x,Percent of Black Population,Percent of Native American Population,Percent of White Population,Percent of Hispanic/Latino Population,Percent of Asian/Pacific Islander Population,Percent of Retired Population
0,None,American Samoa,60000,AS,0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
1,None,Guam,66010,GU,0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
2,None,Mariana Islands,69000,MP,0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
3,None,Saint Croix (County Equivalent),78010,VI,0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
4,None,Saint John (County Equivalent),78020,VI,0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...
3221,None,Greene,01063,AL,5,79.5,0.5,17.1,1.6,0.0,20.4
3222,None,Macon,01087,AL,5,81.7,0.2,15.5,1.7,0.2,18.6
3223,None,Holmes,28051,MS,5,83.7,0.0,15.6,0.2,0.0,14.1
3224,None,Jefferson,28063,MS,5,85.8,0.1,13.0,0.3,0.4,14.9
3225,None,Claiborne,28021,MS,5,87.4,0.1,11.6,0.1,0.5,15.3